project_id = "sloahecvuwtimwtnbxme"

[functions.generate-board]
verify_jwt = false

[functions.companion-chat]
verify_jwt = false

[functions.analyze-diary]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false
